insert into nationality (nationality_id, nationality_name, nationality_code) values
                                                                                 (1, 'Afghanistan', 'AF'),
                                                                                 (2, 'Albania', 'AL'),
                                                                                 (3, 'Algeria', 'DZ'),
                                                                                 (4, 'Argentina', 'AR'),
                                                                                 (5, 'Australia', 'AU'),
                                                                                 (6, 'Austria', 'AT'),
                                                                                 (7, 'Bangladesh', 'BD'),
                                                                                 (8, 'Belgium', 'BE'),
                                                                                 (9, 'Brazil', 'BR'),
                                                                                 (10, 'Canada', 'CA'),
                                                                                 (11, 'Chile', 'CL'),
                                                                                 (12, 'China', 'CN'),
                                                                                 (13, 'Colombia', 'CO'),
                                                                                 (14, 'Czech Republic', 'CZ'),
                                                                                 (15, 'Denmark', 'DK'),
                                                                                 (16, 'Egypt', 'EG'),
                                                                                 (17, 'Finland', 'FI'),
                                                                                 (18, 'France', 'FR'),
                                                                                 (19, 'Germany', 'DE'),
                                                                                 (20, 'Ghana', 'GH'),
                                                                                 (21, 'Greece', 'GR'),
                                                                                 (22, 'Hungary', 'HU'),
                                                                                 (23, 'Iceland', 'IS'),
                                                                                 (24, 'India', 'IN'),
                                                                                 (25, 'Indonesia', 'ID'),
                                                                                 (26, 'Iran', 'IR'),
                                                                                 (27, 'Iraq', 'IQ'),
                                                                                 (28, 'Ireland', 'IE'),
                                                                                 (29, 'Israel', 'IL'),
                                                                                 (30, 'Italy', 'IT'),
                                                                                 (31, 'Japan', 'JP'),
                                                                                 (32, 'Kenya', 'KE'),
                                                                                 (33, 'Malaysia', 'MY'),
                                                                                 (34, 'Mexico', 'MX'),
                                                                                 (35, 'Netherlands', 'NL'),
                                                                                 (36, 'New Zealand', 'NZ'),
                                                                                 (37, 'Nigeria', 'NG'),
                                                                                 (38, 'Norway', 'NO'),
                                                                                 (39, 'Pakistan', 'PK'),
                                                                                 (40, 'Peru', 'PE'),
                                                                                 (41, 'Philippines', 'PH'),
                                                                                 (42, 'Poland', 'PL'),
                                                                                 (43, 'Portugal', 'PT'),
                                                                                 (44, 'Russia', 'RU'),
                                                                                 (45, 'Saudi Arabia', 'SA'),
                                                                                 (46, 'Singapore', 'SG'),
                                                                                 (47, 'South Africa', 'ZA'),
                                                                                 (48, 'South Korea', 'KR'),
                                                                                 (49, 'Spain', 'ES'),
                                                                                 (50, 'Sweden', 'SE'),
                                                                                 (51, 'Switzerland', 'CH'),
                                                                                 (52, 'Thailand', 'TH'),
                                                                                 (53, 'Turkey', 'TR'),
                                                                                 (54, 'Ukraine', 'UA'),
                                                                                 (55, 'United Arab Emirates', 'AE'),
                                                                                 (56, 'United Kingdom', 'UK'),
                                                                                 (57, 'United States', 'US'),
                                                                                 (58, 'Venezuela', 'VE'),
                                                                                 (59, 'Vietnam', 'VN'),
                                                                                 (60, 'Zimbabwe', 'ZW');